# Instrument Configuration Parameters

name = "HiTMIS-A 2021" # instrument name
sigma = "98.76 1 / mm" # groove density (grooves/mm)
# Collimating lens parameters
alpha_ofst = "-67.3 deg" # grating alpha angle offset (deg)
gamma_ofst = "0.0 deg" # grating gamma angle offset (deg)

[col_lens]
fl = "430.0 mm" # focal length (mm)
distance = "100.0 mm" # distance from lens to grating pivot (mm)
# lens offset from nominal position
rotation = "-5.0 deg" # lens rotation (deg)

[col_lens.ofst]
x = "-2.35 mm" # x offset from nominal position
y = "0.0 mm" # y offset from nominal position

[slits.BL]
x = "21.43 mm" # slit X center (mm)
y = "-20.0 mm" # slit Y center (mm)
width = "0.25 mm" # slit width (mm)
height = "40.0 mm" # slit height (mm)
ranges = [["3150.0 Angstrom", "4450.0 Angstrom"], ["7000.0 Angstrom", "8000.0 Angstrom"]] # wavelength ranges (Angstrom)

[slits.BR]
x = "0.0 mm" # slit X center (mm)
y = "-20.0 mm" # slit Y center (mm)
width = "0.25 mm" # slit width (mm)
height = "40.0 mm" # slit height (mm)
ranges = [["4950.0 Angstrom", "10000.0 Angstrom"]] # wavelength ranges (Angstrom)

[slits.TL]
x = "21.43 mm" # slit X center (mm)
y = "20.0 mm" # slit Y center (mm)
width = "0.25 mm" # slit width (mm)
height = "40.0 mm" # slit height (mm)
ranges = [["5900.0 Angstrom", "10000.0 Angstrom"]] # wavelength ranges (Angstrom)

[slits.TR]
x = "0.0 mm" # slit X center (mm)
y = "20.0 mm" # slit Y center (mm)
width = "0.25 mm" # slit width (mm)
height = "40.0 mm" # slit height (mm)
ranges = [["4350.0 Angstrom", "5000.0 Angstrom"]] # wavelength ranges (Angstrom)

[mosaic]
x = "-4.58 deg" # mosaic X center (deg)
y = "0.74 mm" # mosaic Y center offset (mm)
width = "52.5 mm" # mosaic width (mm)
height = "55.19 mm" # mosaic height (mm)
# mosaic windows (filters)
scale = "54.8584 um" # mosaic plate scale (mm/pixel). Same as camera pixel size if camera is at mosaic

[[mosaic.windows]]
x = "23.24 mm" # filter X from mosaic corner origin (mm)
y = "1.94 mm" # filter Y from mosaic corner origin (mm)
width = "29.26 mm" # filter width (mm)
height = "25.02 mm" # filter height (mm)
ranges = [["4805.0 Angstrom", "4925.0 Angstrom"]] # wavelength ranges (Angstrom)
name = "Hβ" # filter name

[[mosaic.windows]]
x = "3.0 mm" # filter X from mosaic corner origin (mm)
y = "1.94 mm" # filter Y from mosaic corner origin (mm)
width = "20.24 mm" # filter width (mm)
height = "25.02 mm" # filter height (mm)
ranges = [["6375.0 Angstrom", "6688.0 Angstrom"]] # wavelength ranges (Angstrom)
name = "Hα" # filter name

[[mosaic.windows]]
x = "38.61 mm" # filter X from mosaic corner origin (mm)
y = "26.96 mm" # filter Y from mosaic corner origin (mm)
width = "13.9 mm" # filter width (mm)
height = "25.02 mm" # filter height (mm)
ranges = [["7724.0 Angstrom", "7824.0 Angstrom"]] # wavelength ranges (Angstrom)
name = "7774" # filter name

[[mosaic.windows]]
x = "29.7 mm" # filter X from mosaic corner origin (mm)
y = "26.96 mm" # filter Y from mosaic corner origin (mm)
width = "8.91 mm" # filter width (mm)
height = "25.02 mm" # filter height (mm)
ranges = [["5550.0 Angstrom", "5650.0 Angstrom"]] # wavelength ranges (Angstrom)
name = "5577" # filter name

[[mosaic.windows]]
x = "20.5 mm" # filter X from mosaic corner origin (mm)
y = "26.96 mm" # filter Y from mosaic corner origin (mm)
width = "9.2 mm" # filter width (mm)
height = "25.02 mm" # filter height (mm)
ranges = [["6270.0 Angstrom", "6370.0 Angstrom"]] # wavelength ranges (Angstrom)
name = "6300" # filter name

[[mosaic.windows]]
x = "3.0 mm" # filter X from mosaic corner origin (mm)
y = "26.96 mm" # filter Y from mosaic corner origin (mm)
width = "17.5 mm" # filter width (mm)
height = "25.02 mm" # filter height (mm)
ranges = [["4200.0 Angstrom", "4300.0 Angstrom"]] # wavelength ranges (Angstrom)
name = "4278" # filter name
# spectral features to mark on the plot

[[features]]
wavelength = "6300.304 Angstrom" # wavelength of interest (Angstrom)
plot_styles = {color = "#d62728"} # plot styles for the feature
name = "6300" # name of the feature

[[features]]
wavelength = "5577.34 Angstrom" # wavelength of interest (Angstrom)
plot_styles = {color = "#2ca02c"} # plot styles for the feature
name = "5577" # name of the feature

[[features]]
wavelength = "7774.17 Angstrom" # wavelength of interest (Angstrom)
plot_styles = {color = "#8c564b"} # plot styles for the feature
name = "7774" # name of the feature

[[features]]
wavelength = "4278.0 Angstrom" # wavelength of interest (Angstrom)
plot_styles = {color = "#9467bd"} # plot styles for the feature
name = "4278" # name of the feature

[[features]]
wavelength = "6562.79 Angstrom" # wavelength of interest (Angstrom)
plot_styles = {color = "#ff7f0e"} # plot styles for the feature
name = "6563" # name of the feature

[[features]]
wavelength = "4861.34 Angstrom" # wavelength of interest (Angstrom)
plot_styles = {color = "#1f77b4"} # plot styles for the feature
name = "4861" # name of the feature
# image transform controls for plotting

[image_transform]
offset_x_mm = 1.5
offset_y_mm = 5.0
rotation_deg = 0.0
scale = 1.07
reflect_axis = "both"
proxy_max_dimension = 512
image_width_px = 1024
image_height_px = 1024
